deploy:  
  environment:  
    name: github-pages  
  needs: build  
  runs-on: ubuntu-latest  
  steps:  
    - name: Checkout  
      uses: actions/checkout@v4  
      with:  
        fetch-depth: 0  
    - name: Deploy to GitHub Pages  
      uses: actions/deploy-pages@v4  
      with:  
        path: docs/.vitepress/dist
